version: '3.1'
services:
  web01:
    container_name: nginx-01
    image: nginx
    ports:
      - 80:80
  db:
    container_name: mysql-db
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: '123456'