version: '3.1'
services:
  web01:
    container_name: web01
    image: nginx-ping:v1
    ports:
      - 80:80
    networks:
      - my-net
  web02:
    container_name: web02
    image: nginx-ping:v1
    ports:
      - 8080:80
    networks:
      - my-net
  web03:
    container_name: web03
    image: nginx-ping:v1
    ports:
      - 8081:80
    networks:
      - my-net
  web04:
    container_name: web04
    image: nginx-ping:v1
    ports:
      - 8082:80
    networks:
      - my-net
networks:
  my-net:

  